# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_sdsim.ipynb.

# %% auto 0
__all__ = ['foo', 'clip_date']

# %% ../nbs/00_sdsim.ipynb 4
def foo(): return 10

# %% ../nbs/00_sdsim.ipynb 5
def clip_date(df_full_range):
    """ 
    This function clips the date based on the below criteria
    Note: If the sales qty is zero in the beginning, the date range is trimmed off
    at the begining, till the first positive sales qty is observed
    """

    # check if sales is 0 at the begining. if yes, trim-off the data to start with first postive sales qty
    start = df_full_range.loc[df_full_range['qty'] > 0].index

    if len(start) > 0:
    # 30 is added because, the bootstrap function required 30 day time window.
    
        if start[0] + 30  < len(df_full_range) :
            date = df_full_range.at[start[0], 'date']
        else:
            date = df_full_range.at[0, 'date']
    else:
        date = df_full_range.at[0, 'date']


    return date
